[tool.poetry]
name = "f1"
version = "0.1.0"
description = "Honza Javorek's personal F1 news feed"
authors = ["Honza Javorek <mail@honzajavorek.cz>"]
readme = "README.md"

[tool.poetry.scripts]
f1 = "f1.__main__:main"

[tool.poetry.dependencies]
python = "^3.12"
crawlee = {extras = ["beautifulsoup"], version = "^0.3.5"}
click = "^8.1.7"
pydantic = "^2.9.2"
feedparser = "^6.0.11"
httpx = "^0.27.2"
lxml = "^5.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
